// ============================================================
// MAFRAN ACESSÓRIOS — produtos de exemplo (usados pelo botão
// "Carregar produtos de exemplo" no painel administrativo,
// só para você ver o catálogo funcionando. Edite / remova
// livremente pelo próprio painel depois.)
// ============================================================

export const SEED_PRODUCTS = [
  {
    nome: "Colar Ponto de Luz",
    categoria: "Colares",
    descricao: "Corrente fininha com zircônia central. Aço inoxidável, não escurece.",
    preco: 89.9,
    precoPromo: 69.9,
    estoque: 12,
    imagem: "",
    ativo: true,
    destaque: true,
  },
  {
    nome: "Colar Corrente Cubana Fina",
    categoria: "Colares",
    descricao: "Elos cubanos delicados, acabamento espelhado.",
    preco: 99.9,
    precoPromo: null,
    estoque: 8,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Colar Coração Duplo",
    categoria: "Colares",
    descricao: "Pingente coração vazado, corrente veneziana curta.",
    preco: 79.9,
    precoPromo: 64.9,
    estoque: 15,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Pulseira Elos Grossos",
    categoria: "Pulseiras",
    descricao: "Elos cubanos grossos, fecho reforçado.",
    preco: 69.9,
    precoPromo: null,
    estoque: 20,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Pulseira Berloques Borboleta",
    categoria: "Pulseiras",
    descricao: "Correntinha fina com berloques de borboleta.",
    preco: 74.9,
    precoPromo: null,
    estoque: 10,
    imagem: "",
    ativo: true,
    destaque: true,
  },
  {
    nome: "Pulseira Veneziana",
    categoria: "Pulseiras",
    descricao: "Elos venezianos clássicos, brilho intenso.",
    preco: 59.9,
    precoPromo: null,
    estoque: 18,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Brinco Argola Texturizada",
    categoria: "Brincos",
    descricao: "Argola média com textura martelada.",
    preco: 49.9,
    precoPromo: null,
    estoque: 25,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Brinco Ponto de Luz Zircônia",
    categoria: "Brincos",
    descricao: "Clássico atemporal, zircônia cristal.",
    preco: 44.9,
    precoPromo: 34.9,
    estoque: 30,
    imagem: "",
    ativo: true,
    destaque: true,
  },
  {
    nome: "Brinco Ear Cuff Folha",
    categoria: "Brincos",
    descricao: "Ear cuff sem furo, formato folha.",
    preco: 39.9,
    precoPromo: null,
    estoque: 14,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Anel Solitário Zircônia",
    categoria: "Anéis",
    descricao: "Aro fino com zircônia solitária cravejada.",
    preco: 54.9,
    precoPromo: null,
    estoque: 16,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Anel Duo Torcido",
    categoria: "Anéis",
    descricao: "Dois aros entrelaçados, acabamento fosco.",
    preco: 49.9,
    precoPromo: null,
    estoque: 0,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Anel Liso Minimalista",
    categoria: "Anéis",
    descricao: "Aro liso 3mm, uso diário.",
    preco: 39.9,
    precoPromo: null,
    estoque: 22,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Relógio Aço Prata Clássico",
    categoria: "Relógios",
    descricao: "Caixa 36mm, pulseira em malha milanesa.",
    preco: 249.9,
    precoPromo: 199.9,
    estoque: 6,
    imagem: "",
    ativo: true,
    destaque: true,
  },
  {
    nome: "Relógio Aço Dourado Slim",
    categoria: "Relógios",
    descricao: "Design slim, mostrador minimalista.",
    preco: 259.9,
    precoPromo: null,
    estoque: 5,
    imagem: "",
    ativo: true,
    destaque: false,
  },
  {
    nome: "Conjunto Colar + Brinco Borboleta",
    categoria: "Conjuntos",
    descricao: "Colar e brinco combinando, motivo borboleta Mafran.",
    preco: 129.9,
    precoPromo: 99.9,
    estoque: 9,
    imagem: "",
    ativo: true,
    destaque: true,
  },
];
